[build]
  base    = ""
  command = "yarn website:build"
  publish = "website/public"

[[redirects]]
  from = "https://react-form-hooks.netlify.com/*"
  to = "https://react-form-hooks.blesswinsamuel.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
